server:
  port: 8085
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/library_system"
    username: "root"
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: true
    cache: false # Set to true in production for performance improvement
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/ # Location of your Thymeleaf templates
    suffix: .html
    template-resolver-order: 1
    servlet:
      content-type: text/html
  flyway:
    url: jdbc:mysql://localhost:3306/library_system
    user: root
    password:
    locations: classpath:db/migration